# Generated by Django 6.0.5 on 2026-05-30 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_delivery_fee', models.BooleanField(default=False)),
                ('has_deduction', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=100)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12)),
                ('deduction', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12)),
                ('payment_received', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12)),
                ('previous_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.sellerprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('boxes', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
