# Generated by Django 5.2.6 on 2026-09-07 06:28

from django.db import migrations, models


def copy_seller_details(apps, schema_editor):
    """Existing invoices keep the seller they were issued with."""
    Invoice = apps.get_model('invoice', 'Invoice')
    for invoice in Invoice.objects.select_related('seller').iterator():
        seller = invoice.seller
        if seller is None:
            continue
        invoice.seller_name = seller.company_name or ''
        invoice.seller_address = seller.address or ''
        invoice.seller_phone = seller.phone or ''
        invoice.seller_bank_account = seller.bank_account or ''
        invoice.seller_fax = seller.fax or ''
        invoice.save(update_fields=[
            'seller_name', 'seller_address', 'seller_phone',
            'seller_bank_account', 'seller_fax',
        ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceitem_boxes_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seller_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_bank_account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_fax',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(copy_seller_details, noop),
    ]
